name: Auto Deploy Backend to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Araksha-smart-disaster-relief-backend
            
            git pull origin dev
            
            mvn clean package -DskipTests
            
            sudo fuser -k 8080/tcp || true
            
            nohup java -jar target/*.jar > app.log 2>&1 &